question: 'Do you provide infrastructure or application metrics?'
depends:
  -
    "on": lot
    being:
      - SaaS
      - saas
      - PaaS
      - paas
      - IaaS
      - iaas
      - SCS
      - scs
type: boolean
validations:
  -
    name: answer_required
    message: 'You need to answer this question.'
followup: analyticsApplicationMetricsDetail