-
  name: Product attributes
  editable: false
  questions:
    - lotName
-
  name: Product name
  editable: true
  questions:
    - serviceName
-
  name: Product description
  editable: true
  questions:
    - serviceSummary
-
  name: Product type
  editable: true
  questions:
    - serviceTypesIaaS
    - serviceTypesSaaS
    - serviceTypesSCS
-
  name: Features and benefits
  editable: true
  questions:
    - serviceFeatures
    - serviceBenefits
-
  name: Constraints
  editable: true
  questions:
    - serviceConstraints
-
  name: User support
  editable: True
  questions:
    - supportTypesEmail
    - supportTypesEmailDetail
    - supportTypesWebchat
    - supportTypesWebchatDetail
    - supportTypesPhone
    - supportTypesPhoneDetail
    - supportResponseTime
    - supportReport
    - supportReportDetail
-
  name: Interface
  editable: True
  questions:
    - interfaceApi
    - interfaceApiDetail
    - interfaceCommandLine
    - interfaceCommandLineDetail
    - interfaceWeb
    - interfaceWebDetail
    - interfaceOther
    - interfaceOtherDetail
-
  name: Guidance
  editable: True
  questions:
    - guidance
-
  name: Analytics
  editable: True
  questions:
    - analyticsApplicationMetrics
    - analyticsApplicationMetricsDetail
    - analyticsNetworkMetrics
    - analyticsNetworkMetricsDetail
    - analyticsOther
    - analyticsOtherDetail
    - analyticsReporting
-
  name: Scaling
  editable: True
  questions:
    - cloudScaleAutomatic
    - cloudScaleAutomaticDetails
    - cloudScaleSelfservice
    - cloudScaleSelfserviceDetails
    - cloudScaleSupport
    - cloudScaleSupportDetails
-
  name: Backups
  editable: True
  questions:
    - cloudBackupScheduled
    - cloudBackupScheduledDetails
    - cloudBackupManual
    - cloudBackupManualDetails
    - cloudBackupSupport
    - cloudBackupSupportDetails
-
  name: Recovery from backups
  editable: True
  questions:
    - cloudRecoverSelfservice
    - cloudRecoverSelfserviceDetails
    - cloudRecoverSupport
    - cloudRecoverSupportDetails
-
  name: Persistent storage
  editable: True
  questions:    
    - cloudPersistent
-
  name: Recovery and resilience plan
  editable: True
  questions:
    - cloudDisasterDetails
-
  name: Provisioning
  editable: True
  questions:
  - provisionCommandline
  - provisionCommandlineDetails
  - provisionApi
  - provisionApiDetails
  - provisionWeb
  - provisionWebDetails
  - provisionOther
  - provisionOtherDetails
-
  name: Onboarding and offboarding
  editable: True
  questions:
  - onboarding
  - offboarding
  - dataExtraction
-
  name: Government networks
  editable: True
  questions:
  - govWan
  - devolved
  - devolvedDetails
-
  name: Data-in-transit protection
  editable: True
  questions:
  - protectDataInTransit
-
  name: Asset protection and resilience
  editable: True
  questions:
  - locationAndLegalJurisdiction
  - dataCentreSecurity
  #- dataCentreSecurityDetail
  #- penTestingFrequency
  #- protectDataAtRest
  #- protectDataAtRestDetail
  #- sanatiseData
  #- sanatiseDataDetail
  #- disposeEquipment
  #- disposeEquipmentDetail
  #- managePhysicalResilience
  #- managePhysicalResilienceDetail
