name: Services the training service works with
question: Which cloud hosting or software services is your training for?

hidden: true
depends:
  - "on": lot
    being:
      - cloud-support

type: list
list_item_name: cloud hosting or software service

validations:
  - name: answer_required
    message: Enter a service.
  - name: under_10_words
    message: Each cloud hosting or software service must be 10 words or fewer.
  - name: max_items_limit
    message: You must have 10 or fewer cloud hosting or software services.
  - name: under_character_limit
    message: Each cloud hosting or software service must be 100 characters or fewer.
