name: Training is tied to specific services
question: Is your training for specific cloud hosting or software services?

hidden: true
depends:
  - "on": lot
    being:
      - cloud-support
followup:
  trainingServiceSpecificList:
    - true

type: boolean

validations:
  - name: answer_required
    message: Select yes if your training is for specific cloud hosting or software services.
