name: Configuration and change management approach
question: Describe your configuration and change management processes.
question_advice: >
    Include details of how:

      - the components of your services are tracked through their lifetime
      - changes are assessed for potential security impact

depends:
  - "on": lot
    being:
      - cloud-hosting
      - cloud-software

type: textbox_large
max_length_in_words: 100

validations:
  - name: answer_required
    message: Enter description.
  - name: under_100_words
    message: Description must be 100 words or fewer.
  - name: under_character_limit
    message: Description must be 1000 characters or fewer.
