name: How the training service works
question: Describe the training you provide.

hidden: true
depends:
  - "on": lot
    being:
      - cloud-support

type: textbox_large
max_length_in_words: 200

validations:
  - name: answer_required
    message: You need to answer this question.
  - name: under_200_words
    message: Your description must be no more than 200 words.
  - name: under_character_limit
    message: Your description must be no more than 2000 characters.

