-
  name: Apply for an opportunity
  editable: True
  questions:
    - availabilitySpecialists
    - availabilityOutcomes
    - dayRate
    - essentialRequirementsMet
    - niceToHaveRequirements
    - respondToEmailAddress