question: How much do you charge per day for a product manager (excluding VAT and expenses)?
question_advice: You won’t be able to charge a higher rate when you apply for opportunities.
depends:
  - "on": lot
    being:
      - digital-specialists
type: pricing
fields:
  minimum_price: productManagerPriceMin
  maximum_price: productManagerPriceMax
field_defaults:
  price_unit: Person
  price_interval: Day

validations:
  - name: answer_required
    field: productManagerPriceMin
    message: 'You need to answer this question.'
  - name: not_money_format
    field: productManagerPriceMin
    message: "Minimum price must be a number, without units, eg 99.95"
  - name: answer_required
    field: productManagerPriceMax
    message: 'You need to answer this question.'
  - name: not_money_format
    field: productManagerPriceMax
    message: "Maximum price must be a number, without units, eg 99.95"
  - name: max_less_than_min
    field: productManagerPriceMax
    message: "Minimum price must be less than maximum price"
