name: Configuration and change management approach
question: Describe your configuration and change management processes.
hint: 50-word limit
question_advice: >
    Include details of how:

      - the components of your services are tracked through their lifetimes
      - changes are assessed for potential security impact

depends:
  - "on": lot
    being:
      - cloud-hosting
      - cloud-software

type: textbox_large

validations:
  - name: answer_required
    message: You need to answer this question.
  - name: under_50_words
    message: Your answer must be no longer than 50 words.
  - name: under_character_limit
    message: Your answer must be no longer than 500 characters.
