name: "Infrastructure or application metrics"
question: "What infrastructure or application metrics do you provide?"
optional: true
depends:
  -
    "on": lot
    being:
      - cloud-hosting

type: checkboxes
options:
    -
        label: "CPU"
    -
        label: "Disk"
    -
        label: "Memory"
    -
        label: "Network"
    -
        label: "Other"
