question: 'Provide a product summary.'
name: 'Product description'
depends:
  -
    "on": lot
    being:
      - cloud-hosting
      - cloud-software
      - cloud-support
type: textbox_large
max_length_in_words: 50
validations:
  -
    name: answer_required
    message: 'You need to answer this question.'
  -
    name: under_50_words
    message: 'Your description must be no more than 50 words.'
  -
    name: under_character_limit
    message: 'Your description must be no more than 500 characters.'
