name: Training tied to specific services
question: Is your training for specific cloud hosting or software services?

depends:
  - "on": lot
    being:
      - cloud-support

type: boolean

validations:
  - name: answer_required
    message: You need to answer this question.
