question: How much do you charge per day for a product manager?
depends:
  - "on": lot
    being:
      - digital-specialists
type: pricing
fields:
  minimum_price: productManagerPriceMin
  maximum_price: productManagerPriceMax
field_defaults:
  price_unit: Person
  price_interval: Day
